server:
  port: 8080
stats-service:
  #url: http://stats-service:9090
  url: http://localhost:9090
feign:
  #url: ${STATS_SERVER_URL:http://stats-service:9090}
  url: ${STATS_SERVER_URL:http://localhost:9090}
spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
    show-sql: false
  sql:
    init:
      mode: always
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ewm_main
    username: root
    password: root
