DROP TABLE IF EXISTS requests;
DROP TABLE IF EXISTS eventCompilationPairs;
DROP TABLE IF EXISTS events;
DROP TABLE IF EXISTS category;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS compilations;
DROP TABLE IF EXISTS locations;

CREATE TABLE users
(
    user_id    BIGINT GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT pk_user
            PRIMARY KEY,
    user_name  VARCHAR(100) UNIQUE NOT NULL,
    user_email VARCHAR(50) UNIQUE  NOT NULL
        CONSTRAINT uq_user_email
            UNIQUE
);

CREATE TABLE locations
(
    location_id BIGINT GENERATED BY DEFAULT AS IDENTITY (MAXVALUE 2147483647)
        CONSTRAINT locations_pk
            PRIMARY KEY,
    longitude   DOUBLE PRECISION NOT NULL,
    latitude    DOUBLE precision NOT NULL
);

CREATE TABLE compilations
(
    compilation_id BIGINT GENERATED BY DEFAULT AS IDENTITY (MAXVALUE 2147483647)
        CONSTRAINT compilations_pk
            PRIMARY KEY,
    pinned         BOOLEAN,
    title          VARCHAR(200) NOT NULL
);

CREATE TABLE category
(
    category_id BIGINT GENERATED BY DEFAULT AS IDENTITY (MAXVALUE 2147483647)
        CONSTRAINT category_pk
            PRIMARY KEY,
    name        VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE events
(
    event_id           BIGINT GENERATED BY DEFAULT AS IDENTITY (MAXVALUE 2147483647)
        CONSTRAINT pk_events
            PRIMARY KEY,
    annotation         VARCHAR(2000)                                    NOT NULL,
    category_id        BIGINT                                           NOT NULL
        CONSTRAINT events_category_category_id_fk
            REFERENCES category,
    description        VARCHAR(7000)                                    NOT NULL,
    event_date         TIMESTAMP                                        NOT NULL,
    location_id        BIGINT                                           NOT NULL
        CONSTRAINT events_locations_location_id_fk
            REFERENCES locations,
    paid               BOOLEAN                                          NOT NULL,
    participant_limit  INTEGER                                          NOT NULL,
    title              VARCHAR(120)                                     NOT NULL,
    initiator_id       BIGINT                                           NOT NULL
        CONSTRAINT events_users_user_id_fk
            REFERENCES users,
    created_on         TIMESTAMP                                        NOT NULL,
    published_on       TIMESTAMP,
    request_moderation BOOLEAN                                          NOT NULL,
    state              VARCHAR(64) DEFAULT 'PENDING'::CHARACTER VARYING NOT NULL
);

CREATE TABLE requests
(
    request_id BIGINT GENERATED BY DEFAULT AS IDENTITY (MAXVALUE 2147483647)
        CONSTRAINT requests_pk
            primary key,
    user_id    BIGINT      NOT NULL
        CONSTRAINT requests_users_user_id_fk
            REFERENCES users,
    event_id   BIGINT      NOT NULL
        CONSTRAINT requests_events_event_id_fk
            REFERENCES events,
    confirmed  VARCHAR(64) NOT NULL DEFAULT 'PENDING'::CHARACTER VARYING,
    created_on TIMESTAMP
);

CREATE TABLE eventcompilationpairs
(
    compilation_id BIGINT NOT NULL
        CONSTRAINT eventcompilationpairs_compilations_compilation_id_fk
            REFERENCES compilations,
    event_id       BIGINT NOT NULL
        CONSTRAINT eventcompilationpairs_events_event_id_fk
            REFERENCES events
);