drop table if exists requests;
drop table if exists eventCompilationPairs;
drop table if exists events;
drop table if exists category;
drop table if exists users;
drop table if exists compilations;
drop table if exists locations;

create table users
(
    user_id    bigint generated by default as identity
        constraint pk_user
            primary key,
    user_name  varchar(100) not null,
    user_email varchar(50)  not null
        constraint uq_user_email
            unique
);

create table locations
(
    location_id bigint generated by default as identity (maxvalue 2147483647)
        constraint locations_pk
            primary key,
    longitude   double precision not null,
    latitude    double precision not null
);

create table compilations
(
    compilation_id bigint generated by default as identity (maxvalue 2147483647)
        constraint compilations_pk
            primary key,
    pinned         boolean,
    title          varchar(200) not null
);

create table category
(
    category_id bigint generated by default as identity (maxvalue 2147483647)
        constraint category_pk
            primary key,
    name        varchar(50) not null
);

create table events
(
    event_id           bigint generated by default as identity (maxvalue 2147483647)
        constraint pk_events
            primary key,
    annotation         varchar(2000)                                    not null,
    category_id        bigint                                           not null
        constraint events_category_category_id_fk
            references category,
    description        varchar(7000)                                    not null,
    event_date         timestamp                                        not null,
    location_id        bigint                                           not null
        constraint events_locations_location_id_fk
            references locations,
    paid               boolean                                          not null,
    participant_limit  integer                                          not null,
    title              varchar(120)                                     not null,
    initiator_id       bigint                                           not null
        constraint events_users_user_id_fk
            references users,
    created_on         timestamp                                        not null,
    published_on       timestamp,
    request_moderation boolean                                          not null,
    state              varchar(64) default 'PENDING'::character varying not null
);

create table requests
(
    request_id bigint generated by default as identity (maxvalue 2147483647)
        constraint requests_pk
            primary key,
    user_id    bigint not null
        constraint requests_users_user_id_fk
            references users,
    event_id   bigint not null
        constraint requests_events_event_id_fk
            references events,
    confirmed  varchar(64) not null default 'PENDING'::character varying,
    created_on timestamp
);

create table eventcompilationpairs
(
    compilation_id bigint not null
        constraint eventcompilationpairs_compilations_compilation_id_fk
            references compilations,
    event_id       bigint not null
        constraint eventcompilationpairs_events_event_id_fk
            references events
);

-----------------------------------------------------------
-- create table if not exists users
-- (
--     user_id    bigint generated by default as identity
--         constraint pk_user
--             primary key,
--     user_name  varchar(100) not null,
--     user_email varchar(50)  not null
--         constraint uq_user_email
--             unique
-- );
--
-- create table if not exists locations
-- (
--     location_id bigint generated by default as identity (maxvalue 2147483647)
--         constraint locations_pk
--             primary key,
--     longitude   double precision not null,
--     latitude    double precision not null
-- );
--
-- create table if not exists compilations
-- (
--     compilation_id bigint generated by default as identity (maxvalue 2147483647)
--         constraint compilations_pk
--             primary key,
--     pinned         boolean,
--     title          varchar(200) not null
-- );
--
-- create table if not exists category
-- (
--     category_id bigint generated by default as identity (maxvalue 2147483647)
--         constraint category_pk
--             primary key,
--     name        varchar(50) not null unique
-- );
--
-- create table if not exists events
-- (
--     event_id           bigint generated by default as identity (maxvalue 2147483647)
--         constraint pk_events
--             primary key,
--     annotation         varchar(2000)                                    not null,
--     category_id        bigint                                           not null
--         constraint events_category_category_id_fk
--             references category,
--     description        varchar(7000)                                    not null,
--     event_date         timestamp                                        not null,
--     location_id        bigint                                           not null
--         constraint events_locations_location_id_fk
--             references locations,
--     paid               boolean                                          not null,
--     participant_limit  integer                                          not null,
--     title              varchar(120)                                     not null,
--     initiator_id       bigint                                           not null
--         constraint events_users_user_id_fk
--             references users,
--     created_on         timestamp                                        not null,
--     published_on       timestamp,
--     request_moderation boolean                                          not null,
--     state              varchar(64) default 'PENDING'::character varying not null
-- );
--
-- create table if not exists requests
-- (
--     request_id bigint generated by default as identity (maxvalue 2147483647)
--         constraint requests_pk
--             primary key,
--     user_id    bigint not null
--         constraint requests_users_user_id_fk
--             references users,
--     event_id   bigint not null
--         constraint requests_events_event_id_fk
--             references events,
--     confirmed  boolean,
--     created_on timestamp
-- );
--
-- create table if not exists eventcompilationpairs
-- (
--     compilation_id bigint not null
--         constraint eventcompilationpairs_compilations_compilation_id_fk
--             references compilations,
--     event_id       bigint not null
--         constraint eventcompilationpairs_events_event_id_fk
--             references events
-- );


--
-- create table if not exists users
-- (
--     user_id bigint generated by default as identity not null
--         constraint pk_user
--             primary key,
--     user_name  varchar(100) not null,
--     user_email varchar(50) not null
--         constraint uq_user_email
--             unique
-- );
--
-- CREATE TABLE if not exists events (
--     --short
--     event_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
--     annotation VARCHAR(2000) NOT NULL,
--     category_id bigint NOT NULL,
--     description VARCHAR(7000) NOT NULL,
--     event_date TIMESTAMP NOT NULL,
--     location_id bigint NOT NULL,
--     paid BOOLEAN NOT NULL,
--     participant_limit INT NOT NULL,
--     title VARCHAR(120) NOT NULL,
--
--     --full
--     initiator_id bigint NOT NULL,
--     created_on TIMESTAMP NOT NULL,
--     published_on TIMESTAMP,
--     request_moderation BOOLEAN NOT NULL,
--     state VARCHAR(64) NOT NULL DEFAULT 'PENDING',
--     CONSTRAINT pk_events PRIMARY KEY (event_id)
-- );
--
-- create table if not exists locations (
--     location_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
--     longitude FLOAT NOT NULL,
--     latitude FLOAT NOT NULL
-- );
--
-- create table if not exists requests (
--     request_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
--     user_id bigint not null,
--     event_id bigint not null,
--     confirmed boolean,
--     created_on timestamp
-- );
--
-- create table if not exists compilations (
--     compilation_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
--     pinned boolean,
--     title varchar(200) not null
-- );
--
-- create table if not exists eventCompilationPairs (
--     compilation_id bigint not null,
--     event_id bigint not null
-- );
--
-- create table if not exists category (
--     category_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
--     name varchar(50) not null
-- );

-------------------------------------------------------------------------





