drop table if exists statistics;

create table if not exists statistics
(
    id bigint generated by default as identity not null
        constraint pk_id
            primary key,
    app  varchar not null,
    uri varchar not null,
    created_on timestamp not null
);
